sources='''# Sources and disclosure\n\n## Aircraft lengths\n- Gulfstream G800: 30.4 m exterior length.\n- Gulfstream G700: 33.48 m, rounded to 33.5 m.\n- Boeing 737 MAX 9 / BBJ basis: 42.1 m.\n- Boeing 787-8: 56.7 m.\n- Airbus A340-300: approximately 63.7 m.\n\n## Ownership / association qualifiers\n- N8628: reported and publicly tracked association with Elon Musk.\n- N11AF: reported association with Jeff Bezos; beneficial-owner data is not public.\n- VT-AKV: publicly reported association with Mukesh Ambani.\n- P4-BDL: linked to Roman Abramovich by the U.S. Department of Commerce.\n- M-IABU: linked to Alisher Usmanov by U.S. Treasury reporting and OCCRP.\n\n## Interior imagery\n- G800 and G700: official Gulfstream model cabin imagery downloaded directly from Gulfstream aircraft pages.\n- BBJ 737 MAX and BBJ 787: Boeing Business Jets cabin imagery, credited on Boeing's model pages.\n- No substitute interior is shown for M-IABU because a verified public cabin source was not established.\n\n## Media treatment\nAll landscape media is rendered with proportional cover-scaling and center-cropping. No source is stretched or non-uniformly scaled.\n'''
(OUT/'sources-and-disclosure.md').write_text(sources,encoding='utf-8')

lessons='''# Private Jets V7 — production lessons and mandatory QC gates\n\n## Problems found in V6\n1. Phrase-by-phrase voice generation created a stitched performance and inconsistent cadence.\n2. Several phrases were accelerated to force the video below a target duration, making the voice unnaturally fast.\n3. Sentence gaps were too short, even where the edit needed a visual beat.\n4. The approved yacht overlay was not actually reused; a different lower-third design was substituted.\n5. Landscape interiors used contain/fit behavior inside a portrait composition. The resulting framing looked squeezed or visually unnatural.\n6. The final review checked frame boundaries but did not enforce source aspect-ratio policy, cadence consistency, or transition continuity.\n\n## V7 fixes\n1. One consistent narration source is used from start to finish. No mid-video voice replacement.\n2. Narration is uniformly slowed to 0.96×; no phrase is independently accelerated.\n3. Pauses are inserted only at sentence/scene boundaries, with a documented 0.20–0.45 s range.\n4. The approved yacht overlay's hierarchy, glass treatment, cyan accent, ghost rank, owner/length split, measurement bar and five-step progress are reused.\n5. Every wide image/video uses `force_original_aspect_ratio=increase` followed by an explicit crop. Stretch and contain-fit are forbidden.\n6. Exterior-to-interior changes happen inside the same rank scene through crossfades while the UI remains stable.\n7. Scene-to-scene transitions use 0.35 s crossfades; hard concatenation is forbidden.\n\n## Mandatory future gates\n- Narration source count must equal one unless a deliberate speaker change is specified.\n- Global speech-speed factor must remain between 0.94 and 1.03. Per-phrase speed changes fail QC.\n- Major sentence pauses must be between 0.18 and 0.65 s unless editorially justified.\n- All landscape media must pass cover-crop manifest checks; any `force_original_aspect_ratio=decrease` or non-uniform `scale=W:H` fails QC.\n- Approved overlay components must be compared against the reference before rendering.\n- Owner/model and numeric metric must use separate measured regions.\n- Every scene midpoint and every transition midpoint must be extracted and reviewed.\n- Final output must be 1080×1920, CFR 60 fps, H.264/AAC, with audio/video duration difference below 0.10 s.\n'''
(OUT/'PRODUCTION_LESSONS_AND_QC.md').write_text(lessons,encoding='utf-8')

# ---- QC ----
final_probe=probe(final); clean_probe=probe(clean)
video_stream=next(s for s in final_probe['streams'] if s['codec_type']=='video'); audio_stream=next(s for s in final_probe['streams'] if s['codec_type']=='audio')
layout_checks=[]
for r in RANKS:
    dummy=Image.new('RGB',(W,H)); dd=ImageDraw.Draw(dummy)
    ow=textw(dd,r['owner'],fit_font(r['owner'],FONT_BOLD,58,664,34))
    lw=textw(dd,f"{r['length']:.1f}",font(FONT_XB,92))
